"""creating tables

Revision ID: 5c41fac4a5ff
Revises: f7823dc468a8
Create Date: 2021-05-24 16:45:55.173061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c41fac4a5ff'
down_revision = 'f7823dc468a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams_gamejams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.Column('gameJamId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gameJamId'], ['gamejams.id'], ),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_teams')
    op.drop_table('teams_gamejams')
    # ### end Alembic commands ###
